### ISSUE TITLE
I cannot find the .npz file

### ISSUE THREAD

**Issue by Hamsss** [tk-rusch/gradientgating#2]
```
def get_data(hom_level=0, graph=1):
  seed = 123456
  dataset = Planetoid('../data', 'Cora')

  if(hom_level==0):
    loader = np.load('data/h0.0' + str(round(hom_level, 3)) + '-r' + str(graph) + '.npz')
  else:
    loader = np.load('data/h0.'+str(round(hom_level,3))+'-r'+str(graph)+'.npz')
```

I was trying to find the .npz file but there is no explanation about the .npz file. 
And also i try to understand about the hom_level, but there is no usage of hom_level.
Can you tell me how to deal with these problem?

**Comment by tk-rusch** [comment]
Hey, as described in the readme file, the data has to be downloaded from here: https://drive.google.com/file/d/1TbC-10pF2WlfbYLmu_gPV8TcXEBYeyOl/view?usp=sharing

**Comment by Hamsss** [comment]
oh, sorry i miss it. thanks for telling me
